# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-18 00:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('createcourse', '0002_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='course',
        ),
    ]
